 preload = /home/dev/.config/dotfiles/wallpapers/bg.png
# wallpaper = ,/home/dev/.config/dotfiles/wallpapers/bg.png
splash = false

wallpaper {
    monitor = eDP-1
    path = /home/dev/.config/dotfiles/wallpapers/bg12.png
    fit_mode = cover
    # splash = false
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/dotfiles/wallpapers/bg12.png
    fit_mode = cover
    # splash = false
}
